#+SETUPFILE: ./config/setupfile.org

#+BEGIN_EXPORT latex
\thispagestyle{firstpagestyle}
\IssueTitle{CPI Report}
\NewsAuthor{Joao Mauricio Rosal, \small\it Chief Economist, PhD}
\NewsEmail{joao.rosal@bgcpartners.com}
\JournalIssue
    \begin{tcolorbox}[colbak=red!5!white, colframe=red!0!white]
      \NewsItem{Key Takeaways}
     \it{\import{latex/}{highlights}}
    \end{tcolorbox}
\vspace{-0.5cm}
#+END_EXPORT

* CPI Report

#+LATEX:\rowcolors{2}{grey!15}{white}
#+INCLUDE: "./org/results.org"
#+caption: Main Figures CPI Figures - June 2017


*Comments*:



#+include: "./html/salutation.html" export html




#+BEGIN_EXPORT latex
\newpage
#+END_EXPORT

* Disclaimer
[[http://www.bgcpartners.com]] \\
\textbf{CONFIDENTIAL:} This document has been sent to you by one of
the BGC entities (collectively BGC) Please see important legal
information and disclaimer relating to this mail at the following
links: http://www.bgcpartners.com/disclaimers/

Please see for BGC Disclosures. The link contains company and FCA
registration numbers. This e-mail, including its contents and
attachments, if any, are confidential. If you are not the named
recipient please notify the sender and immediately delete it. You may
not disseminate, distribute, or forward this e-mail message or
disclose its contents to anybody else. Copyright and any other
intellectual property rights in its contents are the sole property of
BGC and its affiliates. E-mail transmission cannot be guaranteed to be
secure or error-free.  The sender therefore does not accept liability
for any errors or omissions in the contents of this message which
arise as a result of e-mail transmission.  If verification is required
please request a hard-copy version. Although we routinely screen for
viruses, addressees should check this e-mail and any attachments for
viruses. We make no representation or warranty as to the absence of
viruses in this e-mail or any attachments. Please note that to ensure
regulatory compliance and for the protection of our customers and
business, we may monitor and read e-mails sent to and from our
server(s).  The registered offices of the BGC entities are at 1
Churchill Place, London, E14 5RD.  For any issues arising from this
email please reply to the sender.  The FCA register appears at
http://www.FCA.org.uk/register/.  The FCA regulates the financial
services industry in the United Kingdom and is located at 25 The North
Colonnade, Canary Wharf, London, E14 5HS.  BGC Financial LP CFTC Rule
1.55(K) Firm Specific Disclosure Statement


* COMMENT Local Variables
# Local Variables:
# eval: (load-file "./elisp/publishing.el")
# eval: (setq org-emphasis-regexp-components'(" \t('\"{" "- \t.,:!?;'\")}\\" " \t\r\n,\"'" "." 10))
# END:
